[package]
name = "picodraw-software"
version = "0.1.0"
edition = "2024"

[dependencies]
picodraw-core = { path = "../core" }
slotmap = { workspace = true }
bumpalo = { workspace = true }

[dev-dependencies]
image = { workspace = true }