[workspace]
members = [
    ".",
    "crates/core",
    "crates/opengl", 
    "crates/software",

    "crates/core2",
    "crates/opengl2",  
]

[workspace.dependencies]
# tests & benchmarks
gungraun = "0.17.0"
pugl-rs = { git = "https://github.com/blepfx/pugl-rs", features = ["opengl"] }
image = { version = "0.25.5", default-features = false, features = ["webp"] }
yansi = "1.0"

# feature(software)
bumpalo = { version = "3.17", features = ["boxed", "collections"] }

# feature(opengl)
glow = { git = "https://github.com/Quant1um/glow", branch = "main" }

# feature(software) & feature(opengl)
slotmap = "1.0.7"

# feature(derive)
proc-macro2 = "1"
quote = "1"
syn = "2"

[profile.bench]
debug = true

[package]
name = "picodraw"
version = "1.0.0"
edition = "2024"
description = "A smol gpu graphics library"
license = "MIT OR Apache-2.0"
exclude = [
    "tests/drawtest", 
    "tests/drawtest.rs"
]

[dependencies]
picodraw-core2 = { path = "crates/core2", default-features = false }
picodraw-opengl2 = { path = "crates/opengl2", optional = true }
picodraw-software = { path = "crates/software", optional = true }

[dev-dependencies]
gungraun = { workspace = true }
pugl-rs = { workspace = true }
image = { workspace = true }
yansi = { workspace = true }

[features]
default = ["opengl"]
opengl = ["dep:picodraw-opengl2"]
software = ["dep:picodraw-software"]

[[example]]
name = "opengl_circles"

[[example]]
name = "opengl_stress"

[[bench]]
name = "software"
harness = false
required-features = ["software"]
