[package]
name = "picodraw-derive"
version = "1.0.0"
edition = "2024"
description = "A proc-macro crate for picodraw"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }